# Issue 1171

The project is generated by [LoopBack](http://loopback.io).

Test project for issue 1171 that replicates the problem outlined there: https://github.com/strongloop/loopback/issues/1171

Error when trying `GET /Parents` or `POST /Parents` using the Explorer:

    {
      "error": {
        "name": "Error",
        "status": 500,
        "message": "ER_BAD_FIELD_ERROR: Unknown column '_children' in 'field list'",
        "code": "ER_BAD_FIELD_ERROR",
        "errno": 1054,
        "sqlState": "42S22",
        "index": 0,
        "stack": "Error: ER_BAD_FIELD_ERROR: Unknown column '_children' in 'field list'
            at Query.Sequence._packetToError (/home/kenta/code/issue1171/node_modules/loopback-connector-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:48:14)
            at Query.ErrorPacket (/home/kenta/code/issue1171/node_modules/loopback-connector-mysql/node_modules/mysql/lib/protocol/sequences/Query.js:82:18)
            at Protocol._parsePacket (/home/kenta/code/issue1171/node_modules/loopback-connector-mysql/node_modules/mysql/lib/protocol/Protocol.js:271:23)
            at Parser.write (/home/kenta/code/issue1171/node_modules/loopback-connector-mysql/node_modules/mysql/lib/protocol/Parser.js:77:12)
            at Protocol.write (/home/kenta/code/issue1171/node_modules/loopback-connector-mysql/node_modules/mysql/lib/protocol/Protocol.js:39:16)
            at Socket.<anonymous> (/home/kenta/code/issue1171/node_modules/loopback-connector-mysql/node_modules/mysql/lib/Connection.js:82:28)
            at Socket.emit (events.js:107:17)
            at readableAddChunk (_stream_readable.js:163:16)
            at Socket.Readable.push (_stream_readable.js:126:10)
            at TCP.onread (net.js:529:20)
            --------------------
            at Protocol._enqueue (/home/kenta/code/issue1171/node_modules/loopback-connector-mysql/node_modules/mysql/lib/protocol/Protocol.js:135:48)
            at PoolConnection.Connection.query (/home/kenta/code/issue1171/node_modules/loopback-connector-mysql/node_modules/mysql/lib/Connection.js:185:25)
            at runQuery (/home/kenta/code/issue1171/node_modules/loopback-connector-mysql/lib/mysql.js:153:16)
            at /home/kenta/code/issue1171/node_modules/loopback-connector-mysql/lib/mysql.js:199:7
            at Ping.onPing (/home/kenta/code/issue1171/node_modules/loopback-connector-mysql/node_modules/mysql/lib/Pool.js:94:5)
            at Ping.<anonymous> (/home/kenta/code/issue1171/node_modules/loopback/node_modules/continuation-local-storage/context.js:74:17)
            at bound (domain.js:254:14)
            at Ping.runBound [as _callback] (domain.js:267:12)
            at Ping.Sequence.end (/home/kenta/code/issue1171/node_modules/loopback-connector-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
            at Ping.Sequence.OkPacket (/home/kenta/code/issue1171/node_modules/loopback-connector-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:105:8)"
      }
    }

The database I used is on AWS. Here the version info:

- innodb_version: 5.6.21
- version_compile_machine: x86_64
- version_compile_os: Linux


Here the tables:

    CREATE TABLE `parent` (
        `parent_id` INT(11) NOT NULL AUTO_INCREMENT,
        `name` VARCHAR(50) NULL DEFAULT NULL,
        PRIMARY KEY (`parent_id`)
    )
    COLLATE='utf8_general_ci'
    ENGINE=InnoDB
    AUTO_INCREMENT=3;


    CREATE TABLE `child` (
        `child_id` INT(11) NOT NULL AUTO_INCREMENT,
        `parent_id` INT(11) NOT NULL,
        `name` VARCHAR(50) NULL DEFAULT NULL,
        PRIMARY KEY (`child_id`),
        INDEX `FK__parent` (`parent_id`),
        CONSTRAINT `FK__parent` FOREIGN KEY (`parent_id`) REFERENCES `parent` (`parent_id`)
    )
    COLLATE='utf8_general_ci'
    ENGINE=InnoDB;
